'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FinSeA.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #
        '''# Licensed to the Apache Software Foundation (ASF) under one or more
        '''# contributor license agreements.  See the NOTICE file distributed with
        '''# this work for additional information regarding copyright ownership.
        '''# The ASF licenses this file to You under the Apache License, Version 2.0
        '''# (the &quot;License&quot;); you may not use this file except in compliance with
        '''# the License.  You may obtain a copy of the License at
        '''# 
        '''#      http://www.apache.org/licenses/LICENSE-2.0
        '''#
        '''# Unless required by applicable law or agre [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property additional_glyphlist() As String
            Get
                Return ResourceManager.GetString("additional_glyphlist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   Äא
        ''' الله
        '''  اللها
        ''' الله
        '''  اللها
        '''  اللها
        '''  هللا
        '''  اللها
        '''  اللها
        ''' 
        '''  اللها
        ''' 
        '''.
        '''</summary>
        Friend ReadOnly Property allah2_pdf() As String
            Get
                Return ResourceManager.GetString("allah2_pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  אÄ
        ''' الله
        ''' الله
        ''' الله
        ''' الله
        ''' الله
        ''' الله
        ''' الله
        ''' الله
        ''' 
        ''' الله
        ''' 
        '''.
        '''</summary>
        Friend ReadOnly Property allah2_pdf_sorted() As String
            Get
                Return ResourceManager.GetString("allah2_pdf_sorted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Courier() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Courier", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Courier_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Courier_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Courier_BoldOblique() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Courier_BoldOblique", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Courier_Oblique() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Courier_Oblique", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The CWEB System of Structured Documentation
        '''(Version 3.64 — February 2002)
        '''Donald E. Knuth and Silvio Levy
        '''TEX is a trademark of the American Mathematical Society.
        '''Acrobat Reader is a trademark of Adobe Systems Incorporated.
        '''The printed form of this manual is copyright c© 1994 by Addison-Wesley Publishing Company, Inc. All
        '''rights reserved.
        '''The electronic form is copyright c© 1987, 1990, 1993, 2000 by Silvio Levy and Donald E. Knuth.
        '''Permission is granted to make and distribute verbatim copies of the electro [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property cweb_pdf() As String
            Get
                Return ResourceManager.GetString("cweb_pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The CWEB System of Structured Documentation
        '''(Version 3.64 — February 2002)
        '''Donald E. Knuth and Silvio Levy
        '''TEX is a trademark of the American Mathematical Society.
        '''Acrobat Reader is a trademark of Adobe Systems Incorporated.
        '''The printed form of this manual is copyright ©c 1994 by Addison-Wesley Publishing Company, Inc. All
        '''rights reserved.
        '''The electronic form is copyright ©c 1987, 1990, 1993, 2000 by Silvio Levy and Donald E. Knuth.
        '''Permission is granted to make and distribute verbatim copies of the electro [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property cweb_pdf_sorted() As String
            Get
                Return ResourceManager.GetString("cweb_pdf_sorted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tue Jun  5 22:15:55 2001
        '''[California Time]
        '''Dynamic PDF CGI Demo
        '''pad-cache2-1.cache.telstra.net
        '''165.228.129.12
        '''.
        '''</summary>
        Friend ReadOnly Property data_000001_pdf() As String
            Get
                Return ResourceManager.GetString("data_000001_pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tue Jun  5 22:15:55 2001
        '''[California Time]
        '''Dynamic PDF CGI Demo
        '''pad-cache2-1.cache.telstra.net
        '''165.228.129.12
        '''.
        '''</summary>
        Friend ReadOnly Property data_000001_pdf_sorted() As String
            Get
                Return ResourceManager.GetString("data_000001_pdf_sorted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #-------------------------------------------------------------------------------
        '''# Licensed to the Apache Software Foundation (ASF) under one
        '''# or more contributor license agreements.  See the NOTICE file
        '''# distributed with this work for additional information
        '''# regarding copyright ownership.  The ASF licenses this file
        '''# to you under the Apache License, Version 2.0 (the
        '''# &quot;License&quot;); you may not use this file except in compliance
        '''# with the License.  You may obtain a copy of the License at
        '''# 
        '''# http://www. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property expected_errors() As String
            Get
                Return ResourceManager.GetString("expected_errors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  بآُتَّا
        ''' 
        '''.
        '''</summary>
        Friend ReadOnly Property FC60_Times_pdf() As String
            Get
                Return ResourceManager.GetString("FC60_Times_pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  آَُّتاب
        ''' 
        '''.
        '''</summary>
        Friend ReadOnly Property FC60_Times_pdf_sorted() As String
            Get
                Return ResourceManager.GetString("FC60_Times_pdf_sorted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to # ###################################################################################
        '''# Copyright (c) 1997,1998,2002,2007 Adobe Systems Incorporated
        '''# 
        '''# Permission is hereby granted, free of charge, to any person obtaining a
        '''# copy of this documentation file to use, copy, publish, distribute,
        '''# sublicense, and/or sell copies of the documentation, and to permit
        '''# others to do the same, provided that:
        '''# - No modification, editing or other alteration of this document is
        '''# allowed; and
        '''# - The above copyright  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property glyphlist() As String
            Get
                Return ResourceManager.GetString("glyphlist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hello محمد World. 
        '''.
        '''</summary>
        Friend ReadOnly Property hello3_pdf() As String
            Get
                Return ResourceManager.GetString("hello3_pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hello محمد World. 
        '''.
        '''</summary>
        Friend ReadOnly Property hello3_pdf_sorted() As String
            Get
                Return ResourceManager.GetString("hello3_pdf_sorted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Helvetica() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Helvetica", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Helvetica_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Helvetica_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Helvetica_BoldOblique() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Helvetica_BoldOblique", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Helvetica_Oblique() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Helvetica_Oblique", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONTRIBUTIONS TO THE ORIGINAL CODEBASE
        '''
        '''Apache xmpbox is based contributions made to the original PaDaF project
        '''
        '''  Copyright 2010 Atos Worldline SAS
        ''' 
        '''  Licensed by Atos Worldline SAS under one or more
        '''  contributor license agreements.  See the NOTICE file distributed with
        '''  this work for additional information regarding copyright ownership.
        '''  Atos Worldline SAS licenses this file to You under the Apache License, Version 2.0
        '''  (the &quot;License&quot;); you may not use this file except in compliance with
        '''  the Licens [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LICENSE() As String
            Get
                Return ResourceManager.GetString("LICENSE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ich bin Marios test.
        '''$Anhang=/home/im/tmp/AGB.pdf$
        '''$Auftragsnummer=2004001452-001$
        '''$Mandant=1$
        '''$MailTo=mario@ops.co.at$
        '''$User=mario$
        '''Ende
        '''.
        '''</summary>
        Friend ReadOnly Property Liste732004001452_001_0_pdf_0__pdf() As String
            Get
                Return ResourceManager.GetString("Liste732004001452_001_0_pdf_0__pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ich bin Marios test.
        '''$Anhang=/home/im/tmp/AGB.pdf$
        '''$Auftragsnummer=2004001452-001$
        '''$Mandant=1$
        '''$MailTo=mario@ops.co.at$
        '''$User=mario$
        '''Ende
        '''.
        '''</summary>
        Friend ReadOnly Property Liste732004001452_001_0_pdf_0__pdf_sorted() As String
            Get
                Return ResourceManager.GetString("Liste732004001452_001_0_pdf_0__pdf_sorted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Based on source code originally developed in the PaDaF project.
        '''Copyright (c) 2010 Atos Worldline SAS
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property NOTICE() As String
            Get
                Return ResourceManager.GetString("NOTICE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test
        '''.
        '''</summary>
        Friend ReadOnly Property openoffice_test_document_pdf() As String
            Get
                Return ResourceManager.GetString("openoffice_test_document_pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test
        '''.
        '''</summary>
        Friend ReadOnly Property openoffice_test_document_pdf_sorted() As String
            Get
                Return ResourceManager.GetString("openoffice_test_document_pdf_sorted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ====================================================
        '''Apache FontBox &lt;http://pdfbox.apache.org/&gt;
        '''====================================================
        '''
        '''The Apache FontBox library is an open source Java tool for working with
        '''PDF fonts.
        '''
        '''You need Java 5 (or higher) and Maven 2 &lt;http://maven.apache.org/&gt; to
        '''build FontBox. The recommended build command is:
        '''
        '''    mvn clean install
        '''
        '''The default build will compile the Java sources and package the binary
        '''classes into a jar package.
        '''
        '''See the Maven documentation for all [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property README() As String
            Get
                Return ResourceManager.GetString("README", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Release Notes -- Apache PDFBox -- Version 1.8.3
        '''
        '''Introduction
        '''------------
        '''
        '''The Apache PDFBox library is an open source Java tool for working with PDF documents.
        '''
        '''This is an incremental bugfix release based on the earlier 1.8.2 release. It 
        '''contains a couple of fixes and small improvements.
        '''
        '''For more details on all fixes included in this release, please refer to the following
        '''issues on the PDFBox issue tracker at https://issues.apache.org/jira/browse/PDFBOX.
        '''
        '''Bug Fixes
        '''
        '''[PDFBOX-465] - invalid date formats
        '''[ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RELEASE_NOTES() As String
            Get
                Return ResourceManager.GetString("RELEASE_NOTES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  
        ''' 
        '''This is my first page with normal layout. 
        '''This is the second line on the page. 
        ''' 
        ''' 
        ''' 
        ''' 
        '''This is my second page.  It will have a landscape layout. 
        '''Second line here. 
        '''.
        '''</summary>
        Friend ReadOnly Property rotation_pdf() As String
            Get
                Return ResourceManager.GetString("rotation_pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  
        ''' 
        '''This is my first page with normal layout. 
        '''This is the second line on the page. 
        ''' 
        ''' 
        ''' 
        ''' 
        '''This is my second page.  It will have a landscape layout. 
        '''Second line here. 
        '''.
        '''</summary>
        Friend ReadOnly Property rotation_pdf_sorted() As String
            Get
                Return ResourceManager.GetString("rotation_pdf_sorted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Courier: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Times: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Tahoma: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Arial: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Arial Narrow: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Arial Black: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Arial Rounded: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Verdana: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Sans serif: Toto je pokusný text s češtinou – ěščřžýáíé
        '''.
        '''</summary>
        Friend ReadOnly Property sample_fonts_solidconvertor_pdf() As String
            Get
                Return ResourceManager.GetString("sample_fonts_solidconvertor_pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Courier: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Times: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Tahoma: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Arial: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Arial Narrow: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Arial Black: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Arial Rounded: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Verdana: Toto je pokusný text s češtinou – ěščřžýáíé
        '''Sans serif: Toto je pokusný text s češtinou – ěščřžýáíé
        '''.
        '''</summary>
        Friend ReadOnly Property sample_fonts_solidconvertor_pdf_sorted() As String
            Get
                Return ResourceManager.GetString("sample_fonts_solidconvertor_pdf_sorted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line 1 
        '''Line 2 
        ''' 
        '''Line 4 
        '''Underline 5 
        '''BoldLine 6 
        ''' 
        '''ItalicLine 8 
        ''' 
        ''' 
        ''' 
        '''.
        '''</summary>
        Friend ReadOnly Property sampleForSpec_pdf() As String
            Get
                Return ResourceManager.GetString("sampleForSpec_pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line 1 
        '''Line 2 
        ''' 
        '''Line 4 
        '''Underline 5 
        '''BoldLine 6 
        ''' 
        '''ItalicLine 8 
        ''' 
        ''' 
        ''' 
        '''.
        '''</summary>
        Friend ReadOnly Property sampleForSpec_pdf_sorted() As String
            Get
                Return ResourceManager.GetString("sampleForSpec_pdf_sorted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I am a simple pdf.
        '''.
        '''</summary>
        Friend ReadOnly Property simple_openoffice_pdf() As String
            Get
                Return ResourceManager.GetString("simple_openoffice_pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I am a simple pdf.
        '''.
        '''</summary>
        Friend ReadOnly Property simple_openoffice_pdf_sorted() As String
            Get
                Return ResourceManager.GetString("simple_openoffice_pdf_sorted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Obtained from: http://www.srgb.com/usingsrgb.html
        '''
        '''The file &quot;sRGB Color Space Profile.icm&quot; is:
        '''Copyright (c) 1998 Hewlett-Packard Company
        '''
        '''To anyone who acknowledges that the file &quot;sRGB Color Space Profile.icm&quot; 
        '''is provided &quot;AS IS&quot; WITH NO EXPRESS OR IMPLIED WARRANTY:
        '''permission to use, copy and distribute this file for any purpose is hereby 
        '''granted without fee, provided that the file is not changed including the HP 
        '''copyright notice tag, and that the name of Hewlett-Packard Company not be 
        '''used in adverti [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sRGB_Color_Space_Profile_icm_LICENSE() As String
            Get
                Return ResourceManager.GetString("sRGB_Color_Space_Profile_icm_LICENSE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Symbol() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Symbol", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Times_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Times_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Times_BoldItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Times_BoldItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Times_Italic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Times_Italic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Times_Roman() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Times_Roman", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF test that contains the word yadda
        '''.
        '''</summary>
        Friend ReadOnly Property yaddatest_pdf() As String
            Get
                Return ResourceManager.GetString("yaddatest_pdf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF test that contains the word yadda
        '''.
        '''</summary>
        Friend ReadOnly Property yaddatest_pdf_sorted() As String
            Get
                Return ResourceManager.GetString("yaddatest_pdf_sorted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ZapfDingbats() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ZapfDingbats", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
