'/*
' * Licensed to the Apache Software Foundation (ASF) under one or more
' * contributor license agreements.  See the NOTICE file distributed with
' * this work for additional information regarding copyright ownership.
' * The ASF licenses this file to You under the Apache License, Version 2.0
' * (the "License"); you may not use this file except in compliance with
' * the License.  You may obtain a copy of the License at
' *
' *      http://www.apache.org/licenses/LICENSE-2.0
' *
' * Unless required by applicable law or agreed to in writing, software
' * distributed under the License is distributed on an "AS IS" BASIS,
' * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' * See the License for the specific language governing permissions and
' * limitations under the License.
' */
'import org.apache.pdfbox.util.StringUtil;
Imports FinSeA.org.apache.pdfbox.util

Namespace org.apache.pdfbox.persistence.util

    '/**
    ' * helper type for faster mapping of bytes to their hex equivalent.
    ' *
    ' * @author Michael Traut
    ' * @version $Revision: 1.4 $
    ' */
    Public NotInheritable Class COSHEXTable

        Private Sub New()
        End Sub

        ''' <summary>
        ''' ASCII byte values for the hex strings.
        ''' </summary>
        ''' <remarks></remarks>
        Public Shared ReadOnly TABLE As Byte()() = _
        { _
            StringUtil.getBytes("00"), _
            StringUtil.getBytes("01"), _
            StringUtil.getBytes("02"), _
            StringUtil.getBytes("03"), _
            StringUtil.getBytes("04"), _
            StringUtil.getBytes("05"), _
            StringUtil.getBytes("06"), _
            StringUtil.getBytes("07"), _
            StringUtil.getBytes("08"), _
            StringUtil.getBytes("09"), _
            StringUtil.getBytes("0A"), _
            StringUtil.getBytes("0B"), _
            StringUtil.getBytes("0C"), _
            StringUtil.getBytes("0D"), _
            StringUtil.getBytes("0E"), _
            StringUtil.getBytes("0F"), _
            StringUtil.getBytes("10"), _
            StringUtil.getBytes("11"), _
            StringUtil.getBytes("12"), _
            StringUtil.getBytes("13"), _
            StringUtil.getBytes("14"), _
            StringUtil.getBytes("15"), _
            StringUtil.getBytes("16"), _
            StringUtil.getBytes("17"), _
            StringUtil.getBytes("18"), _
            StringUtil.getBytes("19"), _
            StringUtil.getBytes("1A"), _
            StringUtil.getBytes("1B"), _
            StringUtil.getBytes("1C"), _
            StringUtil.getBytes("1D"), _
            StringUtil.getBytes("1E"), _
            StringUtil.getBytes("1F"), _
            StringUtil.getBytes("20"), _
            StringUtil.getBytes("21"), _
            StringUtil.getBytes("22"), _
            StringUtil.getBytes("23"), _
            StringUtil.getBytes("24"), _
            StringUtil.getBytes("25"), _
            StringUtil.getBytes("26"), _
            StringUtil.getBytes("27"), _
            StringUtil.getBytes("28"), _
            StringUtil.getBytes("29"), _
            StringUtil.getBytes("2A"), _
            StringUtil.getBytes("2B"), _
            StringUtil.getBytes("2C"), _
            StringUtil.getBytes("2D"), _
            StringUtil.getBytes("2E"), _
            StringUtil.getBytes("2F"), _
            StringUtil.getBytes("30"), _
            StringUtil.getBytes("31"), _
            StringUtil.getBytes("32"), _
            StringUtil.getBytes("33"), _
            StringUtil.getBytes("34"), _
            StringUtil.getBytes("35"), _
            StringUtil.getBytes("36"), _
            StringUtil.getBytes("37"), _
            StringUtil.getBytes("38"), _
            StringUtil.getBytes("39"), _
            StringUtil.getBytes("3A"), _
            StringUtil.getBytes("3B"), _
            StringUtil.getBytes("3C"), _
            StringUtil.getBytes("3D"), _
            StringUtil.getBytes("3E"), _
            StringUtil.getBytes("3F"), _
            StringUtil.getBytes("40"), _
            StringUtil.getBytes("41"), _
            StringUtil.getBytes("42"), _
            StringUtil.getBytes("43"), _
            StringUtil.getBytes("44"), _
            StringUtil.getBytes("45"), _
            StringUtil.getBytes("46"), _
            StringUtil.getBytes("47"), _
            StringUtil.getBytes("48"), _
            StringUtil.getBytes("49"), _
            StringUtil.getBytes("4A"), _
            StringUtil.getBytes("4B"), _
            StringUtil.getBytes("4C"), _
            StringUtil.getBytes("4D"), _
            StringUtil.getBytes("4E"), _
            StringUtil.getBytes("4F"), _
            StringUtil.getBytes("50"), _
            StringUtil.getBytes("51"), _
            StringUtil.getBytes("52"), _
            StringUtil.getBytes("53"), _
            StringUtil.getBytes("54"), _
            StringUtil.getBytes("55"), _
            StringUtil.getBytes("56"), _
            StringUtil.getBytes("57"), _
            StringUtil.getBytes("58"), _
            StringUtil.getBytes("59"), _
            StringUtil.getBytes("5A"), _
            StringUtil.getBytes("5B"), _
            StringUtil.getBytes("5C"), _
            StringUtil.getBytes("5D"), _
            StringUtil.getBytes("5E"), _
            StringUtil.getBytes("5F"), _
            StringUtil.getBytes("60"), _
            StringUtil.getBytes("61"), _
            StringUtil.getBytes("62"), _
            StringUtil.getBytes("63"), _
            StringUtil.getBytes("64"), _
            StringUtil.getBytes("65"), _
            StringUtil.getBytes("66"), _
            StringUtil.getBytes("67"), _
            StringUtil.getBytes("68"), _
            StringUtil.getBytes("69"), _
            StringUtil.getBytes("6A"), _
            StringUtil.getBytes("6B"), _
            StringUtil.getBytes("6C"), _
            StringUtil.getBytes("6D"), _
            StringUtil.getBytes("6E"), _
            StringUtil.getBytes("6F"), _
            StringUtil.getBytes("70"), _
            StringUtil.getBytes("71"), _
            StringUtil.getBytes("72"), _
            StringUtil.getBytes("73"), _
            StringUtil.getBytes("74"), _
            StringUtil.getBytes("75"), _
            StringUtil.getBytes("76"), _
            StringUtil.getBytes("77"), _
            StringUtil.getBytes("78"), _
            StringUtil.getBytes("79"), _
            StringUtil.getBytes("7A"), _
            StringUtil.getBytes("7B"), _
            StringUtil.getBytes("7C"), _
            StringUtil.getBytes("7D"), _
            StringUtil.getBytes("7E"), _
            StringUtil.getBytes("7F"), _
            StringUtil.getBytes("80"), _
            StringUtil.getBytes("81"), _
            StringUtil.getBytes("82"), _
            StringUtil.getBytes("83"), _
            StringUtil.getBytes("84"), _
            StringUtil.getBytes("85"), _
            StringUtil.getBytes("86"), _
            StringUtil.getBytes("87"), _
            StringUtil.getBytes("88"), _
            StringUtil.getBytes("89"), _
            StringUtil.getBytes("8A"), _
            StringUtil.getBytes("8B"), _
            StringUtil.getBytes("8C"), _
            StringUtil.getBytes("8D"), _
            StringUtil.getBytes("8E"), _
            StringUtil.getBytes("8F"), _
            StringUtil.getBytes("90"), _
            StringUtil.getBytes("91"), _
            StringUtil.getBytes("92"), _
            StringUtil.getBytes("93"), _
            StringUtil.getBytes("94"), _
            StringUtil.getBytes("95"), _
            StringUtil.getBytes("96"), _
            StringUtil.getBytes("97"), _
            StringUtil.getBytes("98"), _
            StringUtil.getBytes("99"), _
            StringUtil.getBytes("9A"), _
            StringUtil.getBytes("9B"), _
            StringUtil.getBytes("9C"), _
            StringUtil.getBytes("9D"), _
            StringUtil.getBytes("9E"), _
            StringUtil.getBytes("9F"), _
            StringUtil.getBytes("A0"), _
            StringUtil.getBytes("A1"), _
            StringUtil.getBytes("A2"), _
            StringUtil.getBytes("A3"), _
            StringUtil.getBytes("A4"), _
            StringUtil.getBytes("A5"), _
            StringUtil.getBytes("A6"), _
            StringUtil.getBytes("A7"), _
            StringUtil.getBytes("A8"), _
            StringUtil.getBytes("A9"), _
            StringUtil.getBytes("AA"), _
            StringUtil.getBytes("AB"), _
            StringUtil.getBytes("AC"), _
            StringUtil.getBytes("AD"), _
            StringUtil.getBytes("AE"), _
            StringUtil.getBytes("AF"), _
            StringUtil.getBytes("B0"), _
            StringUtil.getBytes("B1"), _
            StringUtil.getBytes("B2"), _
            StringUtil.getBytes("B3"), _
            StringUtil.getBytes("B4"), _
            StringUtil.getBytes("B5"), _
            StringUtil.getBytes("B6"), _
            StringUtil.getBytes("B7"), _
            StringUtil.getBytes("B8"), _
            StringUtil.getBytes("B9"), _
            StringUtil.getBytes("BA"), _
            StringUtil.getBytes("BB"), _
            StringUtil.getBytes("BC"), _
            StringUtil.getBytes("BD"), _
            StringUtil.getBytes("BE"), _
            StringUtil.getBytes("BF"), _
            StringUtil.getBytes("C0"), _
            StringUtil.getBytes("C1"), _
            StringUtil.getBytes("C2"), _
            StringUtil.getBytes("C3"), _
            StringUtil.getBytes("C4"), _
            StringUtil.getBytes("C5"), _
            StringUtil.getBytes("C6"), _
            StringUtil.getBytes("C7"), _
            StringUtil.getBytes("C8"), _
            StringUtil.getBytes("C9"), _
            StringUtil.getBytes("CA"), _
            StringUtil.getBytes("CB"), _
            StringUtil.getBytes("CC"), _
            StringUtil.getBytes("CD"), _
            StringUtil.getBytes("CE"), _
            StringUtil.getBytes("CF"), _
            StringUtil.getBytes("D0"), _
            StringUtil.getBytes("D1"), _
            StringUtil.getBytes("D2"), _
            StringUtil.getBytes("D3"), _
            StringUtil.getBytes("D4"), _
            StringUtil.getBytes("D5"), _
            StringUtil.getBytes("D6"), _
            StringUtil.getBytes("D7"), _
            StringUtil.getBytes("D8"), _
            StringUtil.getBytes("D9"), _
            StringUtil.getBytes("DA"), _
            StringUtil.getBytes("DB"), _
            StringUtil.getBytes("DC"), _
            StringUtil.getBytes("DD"), _
            StringUtil.getBytes("DE"), _
            StringUtil.getBytes("DF"), _
            StringUtil.getBytes("E0"), _
            StringUtil.getBytes("E1"), _
            StringUtil.getBytes("E2"), _
            StringUtil.getBytes("E3"), _
            StringUtil.getBytes("E4"), _
            StringUtil.getBytes("E5"), _
            StringUtil.getBytes("E6"), _
            StringUtil.getBytes("E7"), _
            StringUtil.getBytes("E8"), _
            StringUtil.getBytes("E9"), _
            StringUtil.getBytes("EA"), _
            StringUtil.getBytes("EB"), _
            StringUtil.getBytes("EC"), _
            StringUtil.getBytes("ED"), _
            StringUtil.getBytes("EE"), _
            StringUtil.getBytes("EF"), _
            StringUtil.getBytes("F0"), _
            StringUtil.getBytes("F1"), _
            StringUtil.getBytes("F2"), _
            StringUtil.getBytes("F3"), _
            StringUtil.getBytes("F4"), _
            StringUtil.getBytes("F5"), _
            StringUtil.getBytes("F6"), _
            StringUtil.getBytes("F7"), _
            StringUtil.getBytes("F8"), _
            StringUtil.getBytes("F9"), _
            StringUtil.getBytes("FA"), _
            StringUtil.getBytes("FB"), _
            StringUtil.getBytes("FC"), _
            StringUtil.getBytes("FD"), _
            StringUtil.getBytes("FE"), _
            StringUtil.getBytes("FF") _
            }

        ''' <summary>
        ''' ASCII byte values for the hex strings.
        ''' </summary>
        ''' <remarks></remarks>
        Public Shared ReadOnly HEX_TABLE() As String = _
            { _
            "00", _
            "01", _
            "02", _
            "03", _
            "04", _
            "05", _
            "06", _
            "07", _
            "08", _
            "09", _
            "0A", _
            "0B", _
            "0C", _
            "0D", _
            "0E", _
            "0F", _
            "10", _
            "11", _
            "12", _
            "13", _
            "14", _
            "15", _
            "16", _
            "17", _
            "18", _
            "19", _
            "1A", _
            "1B", _
            "1C", _
            "1D", _
            "1E", _
            "1F", _
            "20", _
            "21", _
            "22", _
            "23", _
            "24", _
            "25", _
            "26", _
            "27", _
            "28", _
            "29", _
            "2A", _
            "2B", _
            "2C", _
            "2D", _
            "2E", _
            "2F", _
            "30", _
            "31", _
            "32", _
            "33", _
            "34", _
            "35", _
            "36", _
            "37", _
            "38", _
            "39", _
            "3A", _
            "3B", _
            "3C", _
            "3D", _
            "3E", _
            "3F", _
            "40", _
            "41", _
            "42", _
            "43", _
            "44", _
            "45", _
            "46", _
            "47", _
            "48", _
            "49", _
            "4A", _
            "4B", _
            "4C", _
            "4D", _
            "4E", _
            "4F", _
            "50", _
            "51", _
            "52", _
            "53", _
            "54", _
            "55", _
            "56", _
            "57", _
            "58", _
            "59", _
            "5A", _
            "5B", _
            "5C", _
            "5D", _
            "5E", _
            "5F", _
            "60", _
            "61", _
            "62", _
            "63", _
            "64", _
            "65", _
            "66", _
            "67", _
            "68", _
            "69", _
            "6A", _
            "6B", _
            "6C", _
            "6D", _
            "6E", _
            "6F", _
            "70", _
            "71", _
            "72", _
            "73", _
            "74", _
            "75", _
            "76", _
            "77", _
            "78", _
            "79", _
            "7A", _
            "7B", _
            "7C", _
            "7D", _
            "7E", _
            "7F", _
            "80", _
            "81", _
            "82", _
            "83", _
            "84", _
            "85", _
            "86", _
            "87", _
            "88", _
            "89", _
            "8A", _
            "8B", _
            "8C", _
            "8D", _
            "8E", _
            "8F", _
            "90", _
            "91", _
            "92", _
            "93", _
            "94", _
            "95", _
            "96", _
            "97", _
            "98", _
            "99", _
            "9A", _
            "9B", _
            "9C", _
            "9D", _
            "9E", _
            "9F", _
            "A0", _
            "A1", _
            "A2", _
            "A3", _
            "A4", _
            "A5", _
            "A6", _
            "A7", _
            "A8", _
            "A9", _
            "AA", _
            "AB", _
            "AC", _
            "AD", _
            "AE", _
            "AF", _
            "B0", _
            "B1", _
            "B2", _
            "B3", _
            "B4", _
            "B5", _
            "B6", _
            "B7", _
            "B8", _
            "B9", _
            "BA", _
            "BB", _
            "BC", _
            "BD", _
            "BE", _
            "BF", _
            "C0", _
            "C1", _
            "C2", _
            "C3", _
            "C4", _
            "C5", _
            "C6", _
            "C7", _
            "C8", _
            "C9", _
            "CA", _
            "CB", _
            "CC", _
            "CD", _
            "CE", _
            "CF", _
            "D0", _
            "D1", _
            "D2", _
            "D3", _
            "D4", _
            "D5", _
            "D6", _
            "D7", _
            "D8", _
            "D9", _
            "DA", _
            "DB", _
            "DC", _
            "DD", _
            "DE", _
            "DF", _
            "E0", _
            "E1", _
            "E2", _
            "E3", _
            "E4", _
            "E5", _
            "E6", _
            "E7", _
            "E8", _
            "E9", _
            "EA", _
            "EB", _
            "EC", _
            "ED", _
            "EE", _
            "EF", _
            "F0", _
            "F1", _
            "F2", _
            "F3", _
            "F4", _
            "F5", _
            "F6", _
            "F7", _
            "F8", _
            "F9", _
            "FA", _
            "FB", _
            "FC", _
            "FD", _
            "FE", _
            "FF" _
            }

    End Class

End Namespace
