Namespace org.apache.fontbox.cff

    '/**
    ' * This class represents a standard SID to String mapping.
    ' * @author Villu Ruusmann
    ' * @version $Revision: 1.0 $
    ' */
    Public Class CFFStandardString

        Private Sub New()
        End Sub

        '/**
        ' * This will return the string mapped to the given SID. 
        ' * @param sid the given SID
        ' * @return the mapped string
        ' */
        Public Shared Function getName(ByVal sid As Integer) As String
            Return SID2STR(sid)
        End Function

        Private Shared ReadOnly SID2STR() As String = { _
            ".notdef", _
            "space", _
            "exclam", _
            "quotedbl", _
            "numbersign", _
            "dollar", _
            "percent", _
            "ampersand", _
            "quoteright", _
            "parenleft", _
            "parenright", _
            "asterisk", _
            "plus", _
            "comma", _
            "hyphen", _
            "period", _
            "slash", _
            "zero", _
            "one", _
            "two", _
            "three", _
            "four", _
            "five", _
            "six", _
            "seven", _
            "eight", _
            "nine", _
            "colon", _
            "semicolon", _
            "less", _
            "equal", _
            "greater", _
            "question", _
            "at", _
            "A", _
            "B", _
            "C", _
            "D", _
            "E", _
            "F", _
            "G", _
            "H", _
            "I", _
            "J", _
            "K", _
            "L", _
            "M", _
            "N", _
            "O", _
            "P", _
            "Q", _
            "R", _
            "S", _
            "T", _
            "U", _
            "V", _
            "W", _
            "X", _
            "Y", _
            "Z", _
            "bracketleft", _
            "backslash", _
            "bracketright", _
            "asciicircum", _
            "underscore", _
            "quoteleft", _
            "a", _
            "b", _
            "c", _
            "d", _
            "e", _
            "f", _
            "g", _
            "h", _
            "i", _
            "j", _
            "k", _
            "l", _
            "m", _
            "n", _
            "o", _
            "p", _
            "q", _
            "r", _
            "s", _
            "t", _
            "u", _
            "v", _
            "w", _
            "x", _
            "y", _
            "z", _
            "braceleft", _
            "bar", _
            "braceright", _
            "asciitilde", _
            "exclamdown", _
            "cent", _
            "sterling", _
            "fraction", _
            "yen", _
            "florin", _
            "section", _
            "currency", _
            "quotesingle", _
            "quotedblleft", _
            "guillemotleft", _
            "guilsinglleft", _
            "guilsinglright", _
            "fi", _
            "fl", _
            "endash", _
            "dagger", _
            "daggerdbl", _
            "periodcentered", _
            "paragraph", _
            "bullet", _
            "quotesinglbase", _
            "quotedblbase", _
            "quotedblright", _
            "guillemotright", _
            "ellipsis", _
            "perthousand", _
            "questiondown", _
            "grave", _
            "acute", _
            "circumflex", _
            "tilde", _
            "macron", _
            "breve", _
            "dotaccent", _
            "dieresis", _
            "ring", _
            "cedilla", _
            "hungarumlaut", _
            "ogonek", _
            "caron", _
            "emdash", _
            "AE", _
            "ordfeminine", _
            "Lslash", _
            "Oslash", _
            "OE", _
            "ordmasculine", _
            "ae", _
            "dotlessi", _
            "lslash", _
            "oslash", _
            "oe", _
            "germandbls", _
            "onesuperior", _
            "logicalnot", _
            "mu", _
            "trademark", _
            "Eth", _
            "onehalf", _
            "plusminus", _
            "Thorn", _
            "onequarter", _
            "divide", _
            "brokenbar", _
            "degree", _
            "thorn", _
            "threequarters", _
            "twosuperior", _
            "registered", _
            "minus", _
            "eth", _
            "multiply", _
            "threesuperior", _
            "copyright", _
            "Aacute", _
            "Acircumflex", _
            "Adieresis", _
            "Agrave", _
            "Aring", _
            "Atilde", _
            "Ccedilla", _
            "Eacute", _
            "Ecircumflex", _
            "Edieresis", _
            "Egrave", _
            "Iacute", _
            "Icircumflex", _
            "Idieresis", _
            "Igrave", _
            "Ntilde", _
            "Oacute", _
            "Ocircumflex", _
            "Odieresis", _
            "Ograve", _
            "Otilde", _
            "Scaron", _
            "Uacute", _
            "Ucircumflex", _
            "Udieresis", _
            "Ugrave", _
            "Yacute", _
            "Ydieresis", _
            "Zcaron", _
            "aacute", _
            "acircumflex", _
            "adieresis", _
            "agrave", _
            "aring", _
            "atilde", _
            "ccedilla", _
            "eacute", _
            "ecircumflex", _
            "edieresis", _
            "egrave", _
            "iacute", _
            "icircumflex", _
            "idieresis", _
            "igrave", _
            "ntilde", _
            "oacute", _
            "ocircumflex", _
            "odieresis", _
            "ograve", _
            "otilde", _
            "scaron", _
            "uacute", _
            "ucircumflex", _
            "udieresis", _
            "ugrave", _
            "yacute", _
            "ydieresis", _
            "zcaron", _
            "exclamsmall", _
            "Hungarumlautsmall", _
            "dollaroldstyle", _
            "dollarsuperior", _
            "ampersandsmall", _
            "Acutesmall", _
            "parenleftsuperior", _
            "parenrightsuperior", _
            "twodotenleader", _
            "onedotenleader", _
            "zerooldstyle", _
            "oneoldstyle", _
            "twooldstyle", _
            "threeoldstyle", _
            "fouroldstyle", _
            "fiveoldstyle", _
            "sixoldstyle", _
            "sevenoldstyle", _
            "eightoldstyle", _
            "nineoldstyle", _
            "commasuperior", _
            "threequartersemdash", _
            "periodsuperior", _
            "questionsmall", _
            "asuperior", _
            "bsuperior", _
            "centsuperior", _
            "dsuperior", _
            "esuperior", _
            "isuperior", _
            "lsuperior", _
            "msuperior", _
            "nsuperior", _
            "osuperior", _
            "rsuperior", _
            "ssuperior", _
            "tsuperior", _
            "ff", _
            "ffi", _
            "ffl", _
            "parenleftinferior", _
            "parenrightinferior", _
            "Circumflexsmall", _
            "hyphensuperior", _
            "Gravesmall", _
            "Asmall", _
            "Bsmall", _
            "Csmall", _
            "Dsmall", _
            "Esmall", _
            "Fsmall", _
            "Gsmall", _
            "Hsmall", _
            "Ismall", _
            "Jsmall", _
            "Ksmall", _
            "Lsmall", _
            "Msmall", _
            "Nsmall", _
            "Osmall", _
            "Psmall", _
            "Qsmall", _
            "Rsmall", _
            "Ssmall", _
            "Tsmall", _
            "Usmall", _
            "Vsmall", _
            "Wsmall", _
            "Xsmall", _
            "Ysmall", _
            "Zsmall", _
            "colonmonetary", _
            "onefitted", _
            "rupiah", _
            "Tildesmall", _
            "exclamdownsmall", _
            "centoldstyle", _
            "Lslashsmall", _
            "Scaronsmall", _
            "Zcaronsmall", _
            "Dieresissmall", _
            "Brevesmall", _
            "Caronsmall", _
            "Dotaccentsmall", _
            "Macronsmall", _
            "figuredash", _
            "hypheninferior", _
            "Ogoneksmall", _
            "Ringsmall", _
            "Cedillasmall", _
            "questiondownsmall", _
            "oneeighth", _
            "threeeighths", _
            "fiveeighths", _
            "seveneighths", _
            "onethird", _
            "twothirds", _
            "zerosuperior", _
            "foursuperior", _
            "fivesuperior", _
            "sixsuperior", _
            "sevensuperior", _
            "eightsuperior", _
            "ninesuperior", _
            "zeroinferior", _
            "oneinferior", _
            "twoinferior", _
            "threeinferior", _
            "fourinferior", _
            "fiveinferior", _
            "sixinferior", _
            "seveninferior", _
            "eightinferior", _
            "nineinferior", _
            "centinferior", _
            "dollarinferior", _
            "periodinferior", _
            "commainferior", _
            "Agravesmall", _
            "Aacutesmall", _
            "Acircumflexsmall", _
            "Atildesmall", _
            "Adieresissmall", _
            "Aringsmall", _
            "AEsmall", _
            "Ccedillasmall", _
            "Egravesmall", _
            "Eacutesmall", _
            "Ecircumflexsmall", _
            "Edieresissmall", _
            "Igravesmall", _
            "Iacutesmall", _
            "Icircumflexsmall", _
            "Idieresissmall", _
            "Ethsmall", _
            "Ntildesmall", _
            "Ogravesmall", _
            "Oacutesmall", _
            "Ocircumflexsmall", _
            "Otildesmall", _
            "Odieresissmall", _
            "OEsmall", _
            "Oslashsmall", _
            "Ugravesmall", _
            "Uacutesmall", _
            "Ucircumflexsmall", _
            "Udieresissmall", _
            "Yacutesmall", _
            "Thornsmall", _
            "Ydieresissmall", _
            "001.000", _
            "001.001", _
            "001.002", _
            "001.003", _
            "Black", _
            "Bold", _
            "Book", _
            "Light", _
            "Medium", _
            "Regular", _
            "Roman", _
            "Semibold" _
        }

    End Class

End Namespace